### ISSUE TITLE
Error: Cannot import name 'exprnode'

### ISSUE THREAD

**Issue by unboxedtype** [cjdrake/pyeda#145]
$ python3 --version
Python 3.5.4

$ uname -a
Linux oberon 4.13.16-100.fc25.x86_64 #1 SMP Mon Nov 27 19:52:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/redhat-release 
Fedora release 25 (Twenty Five)

Tried to install using pip, but failed someway and installed using 
$  python3 setup.py install
from sources.

Then, in the shell:
$ python3
Python 3.5.4 (default, Oct  9 2017, 12:07:29) 
[GCC 6.4.1 20170727 (Red Hat 6.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
from pyeda.inter import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shishkin/src/pyeda/pyeda/inter.py", line 24, in <module>
    from pyeda.boolalg.bdd import (
  File "/home/shishkin/src/pyeda/pyeda/boolalg/bdd.py", line 27, in <module>
    from pyeda.boolalg.expr import exprvar, Or, And
  File "/home/shishkin/src/pyeda/pyeda/boolalg/expr.py", line 114, in <module>
    from pyeda.boolalg import exprnode
ImportError: cannot import name 'exprnode'

a, b, c, d = map(exprvar, "abcd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'exprvar' is not defined

Please help :-)

**Comment by unboxedtype** [comment]
Resolved. The issue was with permissions. Somehow I installed pyeda using the root account.
